config/routes.rb
Rails.application.routes.draw do
  resources :user_texts
  resources :texts
  root "texts#index"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get "/login" => "users/sessions#new"
  end
  resources :genres
  resources :artists

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  has_many :artist
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: %i[ show edit update destroy ]
  before_action :check_permission, only: %i[ edit destroy ]

  # GET /genres or /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1 or /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres or /genres.json
  def create
    @genre = Genre.new(genre_params)

    @genre.user_id = current_user.id
    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: "Genre was successfully created." }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1 or /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: "Genre was successfully updated." }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1 or /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: "Genre was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = @exam = Genre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def genre_params
      params.require(:genre).permit(:name, :description)
    end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |form| %>
  <% if genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
        <% genre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Show', @genre %> |
<%= link_to 'Back', genres_path %>

app/views/genres/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Genres</h1>
<% if @genres.blank? %>
  <p> Empty genres</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
          <td><%= genre.description %></td>
          <td><%= link_to 'Show', genre %></td>
          <td><%= link_to 'Edit', edit_genre_path(genre) %></td>
          <td><%= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
<% end %>

<%= link_to 'New Genre', new_genre_path %>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= render 'form', genre: @genre %>

<%= link_to 'Back', genres_path %>

app/views/genres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @genre.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @genre.description %>
</p>

<%= link_to 'Edit', edit_genre_path(@genre) %> |
<%= link_to 'Back', genres_path %>