config/routes.rb
Rails.application.routes.draw do
  resources :user_texts
  resources :texts
  root "texts#index"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get "/login" => "users/sessions#new"
  end
  resources :genres
  resources :artists

end

app/models/text.rb
class Text < ApplicationRecord
  validates :name, :text, presence: true

  belongs_to :artist
  belongs_to :user
  has_many :user_text

end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text, only: %i[ show edit update destroy ]
  before_action :check_permission, only: %i[ edit destroy ]

  # GET /texts or /texts.json
  def index
    @texts = Text.all
  end

  # GET /texts/1 or /texts/1.json
  def show
  end

  # GET /texts/new
  def new
    @text = Text.new
  end

  # GET /texts/1/edit
  def edit
  end

  # POST /texts or /texts.json
  def create
    @text = Text.new(text_params)

    @text.user_id = current_user.id
    respond_to do |format|
      if @text.save
        format.html { redirect_to @text, notice: "Text was successfully created." }
        format.json { render :show, status: :created, location: @text }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /texts/1 or /texts/1.json
  def update
    respond_to do |format|
      if @text.update(text_params)
        format.html { redirect_to @text, notice: "Text was successfully updated." }
        format.json { render :show, status: :ok, location: @text }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /texts/1 or /texts/1.json
  def destroy
    @text.destroy
    respond_to do |format|
      format.html { redirect_to texts_url, notice: "Text was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text
      @text = @exam = Text.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def text_params
      params.require(:text).permit(:name, :text, :artist_id)
    end
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/texts/_form.html.erb
<%= form_with(model: text) do |form| %>
  <% if text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(text.errors.count, "error") %> prohibited this text from being saved:</h2>

      <ul>
        <% text.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, size: '50x50' %>
  </div>

  <div class="field">
    <%= select("text", "artist_id", Artist.all.collect { |p| [p.name, p.id] }) %>
    <%= link_to 'New Artist', new_artist_path %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/texts/edit.html.erb
<h1>Editing Text</h1>

<%= render 'form', text: @text %>

<%= link_to 'Show', @text %> |
<%= link_to 'Back', texts_path %>

app/views/texts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Texts</h1>
<% if @texts.blank? %>
  <p> Empty texts</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Song Name</th>
        <th>Group</th>
        <th>Count of user texts</th>
      </tr>
    </thead>

    <tbody>
      <% @texts.each do |text| %>
        <tr>
          <td><%= link_to text.name, text %></td>
          <td><%= link_to text.artist.name, text.artist %></td>
          <td><%= link_to text.user_text.size, user_texts_path(text_id: text.id ) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
<% end %>

<%= link_to 'New Text', new_text_path %>

app/views/texts/new.html.erb
<h1>New Text</h1>

<%= render 'form', text: @text %>

<%= link_to 'Back', texts_path %>

app/views/texts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @text.name %>
</p>

<p>
  <strong>Artist:</strong>
  <%= link_to @text.artist.name, @text.artist %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @text.artist.genre.name %>
</p>

<p class="test-song">
  <strong>Text:</strong>
  <%= @text.text %>
</p>
<p><%= link_to 'New User Text', new_user_text_path(text_id: @text.id)  %></p>

<%= link_to 'Edit', edit_text_path(@text) %> |
<%= link_to 'Destroy', @text, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', texts_path %>